at_trade_pulse:
  # dbt profile that reads Postgres credentials from environment variables.
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'tradepulse') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'tradepulse') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'tradepulse') }}"
      schema: marts
      threads: 4
